### ISSUE TITLE
Error from MAC OS 

### ISSUE THREAD

**Issue by piggyvenus** [2015-Middleware-Keynote/demo-ansible#104]
Package that I installed on OS X 10.11.3
— Python 2.7.10
— boto-2.39.0
— ansible 2.0.1.0
— click-6.4

Environmental variables below are set. 
AWS_SECRET_ACCESS_KEY=<>
AWS_ACCESS_KEY_ID=<>

Command:
./run.py --no-confirm --deployment-type openshift-enterprise --master-instance-type m4.large --infra-instance-type m4.large --node-instance-type m4.large --keypair workshop --r53-zone sc.osecloud.com --app-dns-prefix apps --rhsm-user user_id --rhsm-pass password --default-password openshift3 --run-smoke-tests --num-smoke-test-users 5 --cluster-id workshop --region us-west-2 --ami ami-775e4f16

Exception:
Traceback (most recent call last):
  File "inventory/aws/hosts/ec2.py", line 800, in <module>
    Ec2Inventory()
  File "inventory/aws/hosts/ec2.py", line 154, in **init**
    self.do_api_calls_update_cache()
  File "inventory/aws/hosts/ec2.py", line 335, in do_api_calls_update_cache
    self.get_route53_records()
  File "inventory/aws/hosts/ec2.py", line 626, in get_route53_records
    r53_conn = route53.Route53Connection()
  File "/Library/Python/2.7/site-packages/boto/route53/connection.py", line 88, in **init**
    profile_name=profile_name)
  File "/Library/Python/2.7/site-packages/boto/connection.py", line 569, in **init**
    host, config, self.provider, self._required_auth_capability())
  File "/Library/Python/2.7/site-packages/boto/auth.py", line 989, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV3Handler'] Check your credentials
Traceback (most recent call last):
  File "./run.py", line 317, in <module>
    launch_demo_env(auto_envvar_prefix='OSE_DEMO')
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(_args, *_kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(_args, **kwargs)
  File "./run.py", line 303, in launch_demo_env
    status = os.system(command)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 830: ordinal not in range(128)

Anyone has seen this error before?
Thanks!

**Comment by juhoffma** [comment]
You have to use ansible 1.9.3

iPhone. iTypos. iApologize.

**Comment by piggyvenus** [comment]
Okay. Thanks for the tip!
Let me try that.

**Comment by piggyvenus** [comment]
Reinstalled Ansible version 1.9.3, but it did not work.

**Comment by juhoffma** [comment]
Hi,

which error do you get now?

-- 
Jürgen Hoffmann
Sent with Airmail

On 24. März 2016 at 21:55:12, piggyvenus (notifications@github.com) wrote:

Reinstalled Ansible version 1.9.3, but it did not work.

**Comment by piggyvenus** [comment]
Hi,
ERROR: Inventory script (inventory/aws/hosts/ec2.py) had an execution error: Traceback (most recent call last):
  File "/Users/shchan/demo-ansible/inventory/aws/hosts/ec2.py", line 800, in <module>
    Ec2Inventory()
  File "/Users/shchan/demo-ansible/inventory/aws/hosts/ec2.py", line 156, in **init**
    self.do_api_calls_update_cache()
  File "/Users/shchan/demo-ansible/inventory/aws/hosts/ec2.py", line 335, in do_api_calls_update_cache
    self.get_route53_records()
  File "/Users/shchan/demo-ansible/inventory/aws/hosts/ec2.py", line 626, in get_route53_records
    r53_conn = route53.Route53Connection()
  File "/Library/Python/2.7/site-packages/boto/route53/connection.py", line 88, in **init**
    profile_name=profile_name)
  File "/Library/Python/2.7/site-packages/boto/connection.py", line 569, in **init**
    host, config, self.provider, self._required_auth_capability())
  File "/Library/Python/2.7/site-packages/boto/auth.py", line 989, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV3Handler'] Check your credentials

I am trying on Fedora now and see if I can get further.
Thanks!

**Comment by piggyvenus** [comment]
I got pass the credentials error if I run the script on Fedora, but I am getting the following error.
[WARNING]: provided hosts list is empty, only localhost is available

PLAY [Bootstrapping environment] *********************************************\* 

TASK: [Validating options] ***************************************************\* 
skipping: [localhost]

TASK: [Launch the CloudFormation Template] ***********************************\* 
failed: [localhost] => {"failed": true}
msg: Stack:arn:aws:cloudformation:us-west-2:270722867670:stack/openshift-demo-shschan/4af26c10-f2b2-11e5-9e39-50ba1b9b0aa6 is in ROLLBACK_COMPLETE state and can not be updated.

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
Launch the CloudFormation Template -------------------------------------- 1.39s
Validating options ------------------------------------------------------ 0.01s
           to retry, use: --limit @/root/bootstrap.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=1  
Is there any other logs for debugging except journalctl? Thanks!

**Comment by thoraxe** [comment]
Once in a while the cloud formation template fails to provision. Just go into your EC2 account and delete it. Once deleted, try again. 

I could try to make some logic to fix this, but it's hard. Ultimately there are some parallelism issues with the CF template but that's hard, too!

**Comment by piggyvenus** [comment]
Thanks for the tips! I will continue to try!

**Comment by piggyvenus** [comment]
I have it working via Fedora. Maybe, I should have started with Fedora. Thanks everyone's help!

**Comment by thoraxe** [comment]
Did you change your keypair when you went to Fedora, or have you confirmed that the keypair works in Fedora and fails in MacOSX?

I would possibly file a BZ against whoever packaged Boto for MacOSX.

I know that @juhoffma uses MacOSX -- what versions of stuff are you using?

**Comment by piggyvenus** [comment]
It used the same keypair and it worked in Fedora.
And it really needs Andible 1.9.4+ for it build successfully  from my test.
Your advice on Cloud Formation helped me to debug all my build issues. Thanks so much!

I have all the versions listed in the beginning of the issue. I am using the same Boto version on both OS.

I would go back to test on Mac again after setting up my workshop. Please advice how to file a BZ for that. 
Sorry for the dumb questions.
