### ISSUE TITLE
"Overhaul" - Amazon ELB - OpenShift Web Console certificate issues

### ISSUE THREAD

**Issue by kenthua** [2015-Middleware-Keynote/demo-ansible#110]
Each master instance has it's own certificate with a CN matching the associated ec2 internal IP (172.x...).  This causes different issues with different browsers.  

When I'm able to successfully login, the console displays alerts such as "Server connection interrupted", unable to get deployment config, etc.  Is it due to certificate issues when ELB is spraying traffic to another server where a certificate may not have been accepted?

Issues go away when only the primary master is InService/enabled in openshift-MasterEx. 

On OSX:
When Firefox is set to "Never remember history" it will keep prompting regarding "Insecure Connection" certificate exception for each individual certificate.

When Firefox set to remember history (this allows for permanently storing the certificate), it will prompt less, but error alerts still pop up.

For Chrome it will prompt only once, but then error alerts pop up.

**Comment by thoraxe** [comment]
Where is the "never remember history" setting in Firefox?

I am using FF 45 on Fedora 22. I only got prompted once.

Sometimes Chrome prompts me a few times.

Internet Explorer works on Windows 7 with only one prompt.

I can't seem to reproduce this issue.

**Comment by kenthua** [comment]
Settings > Preferences > Privacy > History > "Firefox will: ..."

**Comment by thoraxe** [comment]
As a workaround we are creating (for other reasons) an openshift-master.CLUSTERID.R53ZONE entry that points to only one master and bypasses the ELB.

**Comment by douglasawoods** [comment]
Kent,
Wouldn't the better approach be to generate a certificate with all Master
IP addresses in the certificate CN?

-Doug

**Comment by kenthua** [comment]
@douglasawoods I don't believe you can put multiple ips in a CN.  It would normally be a wildcard dns.  I could be wrong.  I guess the question is, should it be the internal IP or the resolvable external address.

**Comment by douglasawoods** [comment]
Kent,
I believe you can put wildcard*sub-domain in a CN, just like the wildcard
we setup in the R53 Zone.

-Doug

**Comment by thoraxe** [comment]
This is a combination problem with demo-ansible and the installer and how the installer generates certificates and what certificates are presented by masters.

The installer, in general, is not great about handling certificates. Given that there is already a workaround (use the openshift-master domain referenced above) I don't see a ton of value in trying to figure out how to generate the right certs and then get them to the masters so that a few users who have a particular setting in Firefox checked don't have issues....
