### ISSUE TITLE
run.py AMI default incorrect?

### ISSUE THREAD

**Issue by kenthua** [2015-Middleware-Keynote/demo-ansible#121]
The run.py references an AMI of `ami-10251c7a` for `us-east-1`  Is it a private AMI?
Should be `ami-2051294a` for `us-east-1`

It appears to have changed on this [commit](https://github.com/2015-Middleware-Keynote/demo-ansible/commit/ee668090ea6c942c2f3510f2f632c12c9589935e#diff-6e38f16215ae91c11fc5c54b74c66d54)

**Comment by thoraxe** [comment]
Yeah that's correct. I'll make a note to fix this.

**Comment by thoraxe** [comment]
If it's any consolation the readme is correct :)
