### ISSUE TITLE
us-east-1 DHCP options domain-name blank

### ISSUE THREAD

**Issue by cooktheryan** [2015-Middleware-Keynote/demo-ansible#131]
When launching in us-east-1 domain-name is blank which causes the openshift nodes to not be able to communicate with the cloud provider correctly. Where as us-west-2 provides a usable DHCP Option set.

us-east-1 fix 
domain-name=ec2.internal
only when region is us-east

**Comment by detiber** [comment]
@cooktheryan I haven't seen this issue with my account in ec2. I'm wondering if it is something that could affect accounts differently.

**Comment by cooktheryan** [comment]
@detiber Actually I'm going to close this. I believe as long as you use the specific openshift-ansible tag you are good. The problem only exists if you attempt to use openshift-ansible master which might be something we want to look at in the future.
