### ISSUE TITLE
Error: lookup plugin (ec2_zones_by_region) not found

### ISSUE THREAD

**Issue by ryanj** [2015-Middleware-Keynote/demo-ansible#132]
I'm seeing this error on the latest `master`, immediately after attempting to create a new environment w/ `region` set to `us-west-1`:

TASK [Launch the CloudFormation Template] **************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "lookup plugin (ec2_zones_by_region) not found"}

**Comment by thoraxe** [comment]
- what versions of things are you using?
- what OS?

**Comment by ryanj** [comment]
I'm using the latest Fedora, with the latest master branches (both repos)

**Comment by thoraxe** [comment]
Yeah latest master is likely to cause you problems.

Readme indicates which tags to use for both repos. Look for an update shortly.

**Comment by ryanj** [comment]
I tried using the tags that are recommended in the README, hit the same error

**Comment by jorgemoralespou** [comment]
@ryanj @thoraxe 
Just went to the same issue and diagnosed with @detiber 
This problem shows up when using ansible 2 and not 1.9.4 as stated in the docs. But a big WARNING needs to be added to the readme.

I'm working on a Vagrant vm to set up a demo-ansible provisioning host. I'll share tomorrow, once working.

**Comment by thoraxe** [comment]
So the fact that we explicitly state what version of Ansible is required is not sufficient?

The prerequiste is:
"Ansible version 1.9.4"

You really feel you need a warning??

**Comment by ryanj** [comment]
I remember [running a quick check for 2.0 support](https://github.com/2015-Middleware-Keynote/demo-ansible/issues/79) a while back, after it's initial release.  However, I know I reverted to 1.9.4 after running the test...  It was fine last month.

Figured it out: Fedora has updated to `ansible-2.0.1.0-2` (F23+), I must have picked it up during a system update. There is an `ansible1.9` package available as well, currently at `ansible1.9-1.9.6-1`.

I'd be in favor of adding an ansible version sanity check to the script if #79 isn't coming soon.

**Comment by jorgemoralespou** [comment]
@thoraxe I think it would be nice to be really called out as a big warning. As you can see, I failed, Ryan failed, and Wanja, from GPTE failed, so yes, I would say it's not enough. Maybe due to the fact that OS X and F23 installs ansible 2 by default.

**Comment by ryanj** [comment]
I'll offer a doc patch / bandaid: https://github.com/2015-Middleware-Keynote/demo-ansible/pull/138

And, create a [new Issue for adding an ansible version sanity check](https://github.com/2015-Middleware-Keynote/demo-ansible/issues/139)

**Comment by ryanj** [comment]
The script is working much better after including the changes from #138.

Thanks for helping troubleshoot! @thoraxe @jorgemoralespou @detiber
