### ISSUE TITLE
Using the included hexboard project.   see hexboard pods but no sketchpod pods

### ISSUE THREAD

**Issue by alberttwong** [2015-Middleware-Keynote/demo-ansible#134]
Here's a screenshot
<img width="1020" alt="screen shot 2016-04-25 at 4 50 15 pm" src="https://cloud.githubusercontent.com/assets/749093/14802476/ebdaaf82-0b05-11e6-8b3a-bf0ddb3ae586.png">

**Comment by thoraxe** [comment]
This is by design. The hexboard demo is:

1) show hexboard is deployed
2) add a sketchpod (show builds)
3) scale up sketchpod
4) "use" app.
