### ISSUE TITLE
 Error fetching memory/usage for container hexboard.Could not connect to metrics service.

### ISSUE THREAD

**Issue by alberttwong** [2015-Middleware-Keynote/demo-ansible#135]
When you try to see metrics, (in my case, I tried to look at hexboard) you get an error. 

<img width="1148" alt="screen shot 2016-04-25 at 5 08 55 pm" src="https://cloud.githubusercontent.com/assets/749093/14802781/6e5080b6-0b08-11e6-9750-19a21489a7b3.png">

**Comment by thoraxe** [comment]
Because you didn't accept the hawkular certificate. Which isn't documented (in this repo) but I will add that to the docs soon.
