### ISSUE TITLE
What do you do if the cleanup script doesn't work?

### ISSUE THREAD

**Issue by alberttwong** [2015-Middleware-Keynote/demo-ansible#143]
Clean script doesn't work.  What do we do then?

![virtualbox_centos 7_27_04_2016_14_44_16](https://cloud.githubusercontent.com/assets/749093/14869162/91279514-0c86-11e6-8506-87261e89ba43.png)

**Comment by thoraxe** [comment]
Did you look in the troubleshooting section of the README where it tells
you what to do?

**Comment by alberttwong** [comment]
Yes.   Deleting the cloudformation profile doesn't work.   It won't provision the environment again.  So the question is what are all the items I need to clean out of AWS to get it working.

**Comment by thoraxe** [comment]
Define "deleting the cloud formation profile doesn't work". Did you go into
AWS and delete the cloudformation? What happened? Did you try deleting it
again? The only thing to do is delete the cloudformation, and possibly the
DNS entry.

Everything is attached to the CF except for one DNS entry.

I'm not sure what isn't clear?
On Apr 27, 2016 7:20 PM, "Albert Wong" notifications@github.com wrote:

Yes. Deleting the cloudformation profile doesn't work. It won't provision
the environment again. So the question is what are all the items I need to
clean out of AWS to get it working.

**Comment by alberttwong** [comment]
I'm closing this issue.   I pulled out the logs and there is a subnet issue on us-west-1.  I don't know why there is a subnet issue on us-west-1 but I don't have the problem on us-west-2.   So there has to be a difference.

**Comment by detiber** [comment]
@alberttwong any info you can provide on the subnet issue? I'm wondering if it has to do with the AZ not supporting VPCs, or the instance type you are selecting, or some other reason.

**Comment by kenthua** [comment]
There must be something in @alberttwong EC2 environment, because I don't have any issues with us-west-1

**Comment by alberttwong** [comment]
The only way I got this working was NOT use US-WEST-1 (N. Cal) and use US-WEST-2 (Oregon).  So my summary is that if all else fails... use another AWS region.

**Comment by alberttwong** [comment]
related https://github.com/2015-Middleware-Keynote/demo-ansible/issues/144

**Comment by thoraxe** [comment]
How is #144 related?

**Comment by alberttwong** [comment]
so I'm asking why I need to do clean up the environment if delete CF doesn't work and the cleanup script doesn't work.    What are all the things I need to look for to delete/reset so that I can use us-west-1.

**Comment by thoraxe** [comment]
I don't know why you can't use us-west-1 or what is causing your issues there. 

If the cleanup _script_ fails you need to go into AWS and delete the CF stack and the single DNS entry that remains. I believe this is covered in the README. There is nothing else to delete.
