### ISSUE TITLE
best practice.   console should be at 443 not 8443 due to security policy

### ISSUE THREAD

**Issue by alberttwong** [2015-Middleware-Keynote/demo-ansible#145]
at some places.   Didn't encounter this issue at the Marriott but Veer told me that it happened to him.

**Comment by detiber** [comment]
I know at one point we were overriding the default port to be 443, but it somehow was reverted along the way.

If you add the following to your invocation of run.py, it will override the port: `--api-port 443 --console-port 443`

**Comment by detiber** [comment]
@thoraxe your thoughts on making 443 the default again?

**Comment by thoraxe** [comment]
I don't have any serious objection to moving the default to 443. That would be an easy PR.

**Comment by thoraxe** [comment]
The default seems to have been 443 for a while.
