### ISSUE TITLE
ERROR: file could not read: /Users/myuser/ansible-scripts/aos-ansible/playbooks/roles/ops_mirror_bootstrap/tasks/main.yml

### ISSUE THREAD

**Issue by debianmaster** [2015-Middleware-Keynote/demo-ansible#156]
Did following

``` sh
cd /home/user/ansible-scripts
git clone https://github.com/2015-Middleware-Keynote/demo-ansible.git
cd demo-ansible
git checkout demo-ansible-2.2.1
cd ..
git clone https://github.com/thoraxe/openshift-ansible.git
cd openshift-ansible
git fetch origin :remotes/origin/openshift-ansible-3.0.94-1-hotfix
git checkout openshift-ansible-3.0.94-1-hotfix
```

`./run.py`

encountered following error

``` sh
ERROR: file could not read: /Users/jjonagam/ansible-scripts/aos-ansible/playbooks/roles/ops_mirror_bootstrap/tasks/main.yml
```

**Comment by piggyvenus** [comment]
Same error for me too.

**Comment by thoraxe** [comment]
At what point did you encounter that error? Can you include the entire output of the sequence after `run.py`?

It shouldn't be looking for those files/scripts unless you are trying to use aos repos. But perhaps I need to refactor something.

**Comment by piggyvenus** [comment]
I don't get the error any more, but it looks like it only install 3.1 (even I removed the line "openshift_package_version.." in openshift_setup.yml.). 
Thanks for the reply.

**Comment by thoraxe** [comment]
Please open a separate issue if you are having problems installing other versions. I have a suspicion I know why you are having that issue.

**Comment by piggyvenus** [comment]
okay. Thanks!

**Comment by WilliamHJKL** [comment]
Same here,
$ ./run.py --cluster-id demo --num-nodes 3 --num-infra 1 --hexboard-size tiny --deployment-type openshift-enterprise --region us-east-1 --ami ami-2051294a --infra-instance-type m4.large --keypair mykey --r53-zone myzone.org --rhsm-user myuser --rhsm-pass mypass --verbose

The error message is : 
We are running: ansible-playbook -i inventory/aws/hosts -e 'cluster_id=demo     ec2_region=us-east-1     ec2_image=ami-2051294a     ec2_keypair=mykey     ec2_master_instance_type=m4.large     ec2_infra_instance_type=m4.large     ec2_node_instance_type=m4.large     r53_zone=myzone.org     r53_host_zone=demo.myzone.org     r53_wildcard_zone=apps.demo.myzone.org     console_port=443     api_port=443     num_app_nodes=3     num_infra_nodes=1     num_masters=3     hexboard_size=tiny     deployment_type=openshift-enterprise     package_version=-3.2.0.44     rhsm_user=myuser     rhsm_pass=mypass  skip_subscription_management=False   use_certificate_repos=False     aos_repo=None     prerelease=False     kerberos_user=None     kerberos_token=None     registry_url=registry.access.redhat.com/openshift3/ose-${component}:${version}     run_smoke_tests=False     run_only_smoke_tests=False     num_smoke_test_users=5     default_password=openshift3' playbooks/openshift_setup.yml -v
ERROR: file could not read: /home/myuser/ansible-scripts/aos-ansible/playbooks/roles/ops_mirror_bootstrap/tasks/main.yml
If I comment out the line : 
    #  - include: ../../aos-ansible/playbooks/roles/ops_mirror_bootstrap/tasks/main.yml
    #vars:
      #  omb_aos_repo: "{{ aos_repo }}"
      #when: use_certificate_repos | bool
   #  - include: ../../aos-ansible/playbooks/roles/qe_registry_bootstrap/tasks/main.yml
    #vars:
      #  omb_aos_repo: "{{ aos_repo }}"
      #  qe_openshift_kerberos_user: "{{ kerberos_user }}"
      #   qe_openshift_token: "{{ kerberos_token }}"
      #when: use_certificate_repos | bool and prerelease | bool
No more errors.

**Comment by thoraxe** [comment]
I think we need to use a "when" on the include, assuming that's supported. Might need to separate out that aos stuff into a separate playbook.
