### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by WilliamHJKL** [2015-Middleware-Keynote/demo-ansible#160]
in run.py : 
@click.option('--package-version', help='OpenShift Package version (eg: 3.2.0.44)',
              show_default=True, default='3.2.0.44')
in playbooks/subscriptions_and_repos.yml 
 command: subscription-manager repos --enable=rhel-7-server-ose-3.1-rpms

So we need to use --package-version 3.1.1.6  to prevent an installation pb.

**Comment by thoraxe** [comment]
Fixed by #161 although now you're forced to 3.2 no matter what. Good enough.
