### ISSUE TITLE
create set # of users with passwords

### ISSUE THREAD

**Issue by thoraxe** [2015-Middleware-Keynote/demo-ansible#20]
We should allow for the user running this installer to specify a # of users to create and possibly an arbitrary password, which will go into the htpasswd file.

This will aid in roadshow environments.

For example, create 40 users user[01-40] with the password "foobar"

**Comment by thoraxe** [comment]
This works:

```
  --run-smoke-tests               Run workshop smoke tests
  --num-smoke-test-users INTEGER  Number of smoke test users  [default: 5]
```

But we currently only set the password to be the cluster-id, so it still would be nice to be able to pass in a password for the smoke test users.

**Comment by detiber** [comment]
I believe this issue has been addressed now.
