### ISSUE TITLE
Optimize initial build for sketchpod

### ISSUE THREAD

**Issue by ryanj** [2015-Middleware-Keynote/demo-ansible#34]
The initial Sketchpod build usually takes about 90s. 

Subsequent builds usually meet our performance expectations, building in under 30s.

Short-term workaround for presenters:  Run a Sketchpod build before your demo

**Comment by thoraxe** [comment]
It looks like we're building a hexboard project and hexboard app, but not building a sketchpod:

https://github.com/2015-Middleware-Keynote/demo-ansible/blob/master/playbooks/util_playbooks/post_setup.yml#L187-L192

**Comment by thoraxe** [comment]
OK I understand the issue now. What it sounds like you want is:

1) build sketchpod
2) deploy sketchpod
3) delete deployed pod / scale to zero
4) run a 2nd build as the "first build"

Or sort of?

**Comment by thoraxe** [comment]
So I thought about this for a few moments, and I think this falls back on the priming the registry with the node layer bit. Running a build before your demo and then deleting all of those things actually won't result in a faster second build. You would only get a faster second build if you re-built the thing you already built, if I understand correctly...

**Comment by ryanj** [comment]
You're probably right - I'm not sure about the best way to optimize this bit.  I should have tested the workaround suggestion before posting it.  

I know we were able to run builds in under 30s for the RHSummit keynote.  Although for me, 90s isn't bad for a workshop pace.  

I think @burrsutter wanted to make sure that we are able to get it back down to 30s for any future Keynote-scale presentations.

**Comment by detiber** [comment]
This has been fixed with the latest changes.
