### ISSUE TITLE
[rfe] improve "wait for registry" task

### ISSUE THREAD

**Issue by thoraxe** [2015-Middleware-Keynote/demo-ansible#42]
There is a task:

```
TASK: [Wait for 60 seconds for registry to re-deploy] ************************* 
```

This could probably be improved with retries and looking at the output of a couple of different commands. A wrote pause is probably not the greatest...

**Comment by detiber** [comment]
This should be fixed now.

**Comment by thoraxe** [comment]
https://github.com/2015-Middleware-Keynote/demo-ansible/blob/master/playbooks/util_playbooks/post_setup.yml#L142

It looks like we're still hard waiting for 60 seconds...
