### ISSUE TITLE
max pods per node

### ISSUE THREAD

**Issue by thoraxe** [2015-Middleware-Keynote/demo-ansible#48]
Did we lose this setting? I am seeing 40 pods in the get node output in a running env. I recall some "kubelet args" task but can't find it in demo-ansible... ?

**Comment by detiber** [comment]
The issue turns out to be a bug in the implementation I added to openshift_ansible.  Fix is available here: https://github.com/openshift/openshift-ansible/pull/490

**Comment by detiber** [comment]
This also required a fix in demo-ansible, which has been merged to master now.

**Comment by thoraxe** [comment]
Fixed by https://github.com/openshift/openshift-ansible/pull/491
