### ISSUE TITLE
when smoke app is already fully deployed but not scaled, re-running demo-ansible doesn't end up scaling

### ISSUE THREAD

**Issue by thoraxe** [2015-Middleware-Keynote/demo-ansible#53]
I think we need some detection logic improvement to the scaling task.

**Comment by ryanj** [comment]
+1 I hit a similar issue recently in Seattle.

I logged into the master to run the scale-up manually, hoping for more information about the failure:

``` bash
for user in {00..60}
do 
  echo "user${user}:" && oc scale rc/smoke-1 --replicas=2 --namespace=user${user}-smoke; 
done
```

This script showed that one of 60 builds (user21) had failed to scale.  I logged in as user21 and found a build failure: https://gist.github.com/ryanj/b34dd0b55c9714fc9538

I re-ran the build for user21, and then the playbook was able to finish successfully.
