### ISSUE TITLE
error while evaluating conditional: deployment_type

### ISSUE THREAD

**Issue by ryanj** [2015-Middleware-Keynote/demo-ansible#54]
@burrsutter and I are both seeing this error while attempting to create environments using the latest `demo-ansible` (cb37666) and `openshift-ansible` (34465b6):

```
TASK: [os_firewall | Install firewalld packages] ****************************** 
fatal: [ec2-52-23-211-8.compute-1.amazonaws.com] => error while evaluating conditional: deployment_type in ['enterprise','openshift-enterprise','origin']
```

**Comment by ryanj** [comment]
The roadshow environments are currently using `openshift-ansible` at `3efe322` - https://github.com/openshift/openshift-ansible/commit/3efe322c2621e1ba19a5bfc1e7b13bb8bd1177ef

For a short-term workaround switch to that commit of `openshift-ansible`:

```
cd ../openshift-ansible
git checkout 3efe322c2621e1ba19a5bfc1e7b13bb8bd1177ef
cd -
```

Then re-run your playbook script.

**Comment by ryanj** [comment]
Hmm...  that didn't seem to fix things.  The script hits an error while pulling down the base / builder images.

**Comment by ryanj** [comment]
Any ideas @thoraxe. @sdodson?

**Comment by sdodson** [comment]
Yes, add `deployment_type='origin'` or `deployment_type='enterprise'` to your inventory with the value you'd like.

**Comment by ryanj** [comment]
I tried adding each of the following to my `inventory/aws/hosts/ec2.ini` file, but I didn't find a winning combo:

```
deployment_type='enterprise'
```

```
deployment_type = enterprise
```

```
deployment_type = openshift-enterprise
```

```
[OSEv3:vars]
deployment_type = enterprise
```

**Comment by thoraxe** [comment]
Are you doing this on your own machine?

**Comment by burrsutter** [comment]
I am running the demo-ansible playbook from my laptop but targeting EC2 - do you feel like running the playbook from a EC2 running VM would be better?

**Comment by thoraxe** [comment]
Not necessarily related. I wasn't sure if Ryan was using our pre staged
environment which has an older version of this repo and the installer repo.

**Comment by ryanj** [comment]
I've been using my laptop and targeting my personal EC2 account in order to work on a fix (based on the latest master branches).  I think I have one ready (#55).

Anyone care to give #55 a quick look?

I was going to verify the fix using our shared Roadshow environment next.  If the branch runs well over there, then I'll probably go ahead and merge (barring any objections).

**Comment by thoraxe** [comment]
Please do not change the roadshow environment.

**Comment by ryanj** [comment]
@thoraxe np, I'm happy to let you handle that work.  I'm running a Roadshow on Monday, so I was hoping to get the fix implemented before everyone leaves for the weekend.

**Comment by detiber** [comment]
Closing, since I believe this has already been addressed.
