### ISSUE TITLE
Error (permission denied) while trying to execute /tmp/registry.sh

### ISSUE THREAD

**Issue by mekenthompson** [2015-Middleware-Keynote/demo-ansible#58]
- shell: /tmp/registry.sh
  register: registry_uri_out

Output:

TASK: [Deploy registry inspection script] ************************************\* 
changed: [openshift-master.demo.***] => {"changed": true, "checksum": "c96092b0e8807086fe7600bf5f9cbb09a163ff60", "dest": "/tmp/registry.sh", "gid": 0, "group": "root", "md5sum": "50610eed0bad5127195a63fd33a4ade4", "mode": "0644", "owner": "root", "secontext": "unconfined_u:object_r:user_home_t:s0", "size": 113, "src": "/home/openshift/.ansible/tmp/ansible-tmp-1444971199.63-41890618638278/source", "state": "file", "uid": 0}

TASK: [shell /tmp/registry.sh] ***********************************************\* 
failed: [openshift-master.demo.***] => {"changed": true, "cmd": "/tmp/registry.sh", "delta": "0:00:00.002316", "end": "2015-10-16 00:58:33.043810", "rc": 126, "start": "2015-10-16 00:58:33.041494", "warnings": []}
stderr: /bin/sh: /tmp/registry.sh: Permission denied

FATAL: all hosts have already failed -- aborting

**Comment by detiber** [comment]
Closing since https://github.com/2015-Middleware-Keynote/demo-ansible/issues/60 should have addressed this.
