### ISSUE TITLE
cannot install: This playbook requires g_lb_group to be set

### ISSUE THREAD

**Issue by christian-posta** [2015-Middleware-Keynote/demo-ansible#64]
Ran into this issue when using latest master from github.com/openshift/openshift-ansible

Seems to be affected by these commits:

https://github.com/openshift/openshift-ansible/commit/ca9f4f08fbf14f9edfa7331e327cf92a25cd4401
https://github.com/openshift/openshift-ansible/commit/c84677a90bd168b804cae7e511747b7af30ce387

Would be easy enough to add these vars here:
https://github.com/2015-Middleware-Keynote/demo-ansible/blob/master/playbooks/openshift_setup.yml#L89

Though not sure what type of LB would be necessary?

**Comment by detiber** [comment]
This has been addressed here: https://github.com/2015-Middleware-Keynote/demo-ansible/pull/63

The variable is used for the native ha installation. Not applicable to demo-ansible, since we only deploy a single master.
