### ISSUE TITLE
[RFE] accept zone + prefix instead of just zone

### ISSUE THREAD

**Issue by thoraxe** [2015-Middleware-Keynote/demo-ansible#7]
For roadshow purposes, it would be nice if we could prompt for zone+prefix instead of just zone.

Eg:

```
zone [base.dns.com]
prefix [someevent]
apps [apps.someevent.base.dns.com]
```

Then we would end up with hosts like:

```
master.someevent.base.dns.com
node1.someevent.base.dns.com
```

And so on and so forth. This also allows multiple clusters to be provisioned into the same DNS zone which saves money.

**Comment by thoraxe** [comment]
This is fixed by https://github.com/thoraxe/demo-ansible/tree/dns-zone-reduce but is pending a workaround for https://github.com/ansible/ansible-modules-core/issues/1816

**Comment by detiber** [comment]
Closing, addressed in https://github.com/2015-Middleware-Keynote/demo-ansible/issues/16
