### ISSUE TITLE
No Package matching 'atomic-openshift' found available, installed or updated

### ISSUE THREAD

**Issue by ryanj** [2015-Middleware-Keynote/demo-ansible#71]
```
TASK: [openshift_master_ca | Install the base package for admin tooling] ****** 
failed: [openshift-master.evgus.openshift3roadshow.com] => {"changed": false, "failed": true, "rc": 0, "results": []}
msg: No Package matching 'atomic-openshift' found available, installed or updated

FATAL: all hosts have already failed -- aborting
```

**Comment by detiber** [comment]
Sounds like the host doesn't have access to the 3.1 repo.

**Comment by ryanj** [comment]
What AMI should I be using?  I have RHEL-7.2_HVM_GA-20151112-x86_64

**Comment by detiber** [comment]
That ami should be fine. Any RHEL 7 ami should work.

**Comment by ryanj** [comment]
This might have been related to use of the (deprecated?) `--skip-subscription-management` flag.

**Comment by thoraxe** [comment]
Yes, I think you're correct. I've never gotten this error. Would you be opposed to closing this and re-opening if you see it again?

**Comment by ryanj** [comment]
yep, np. Thanks
