### ISSUE TITLE
[rfe] check for subscription status before trying to register

### ISSUE THREAD

**Issue by thoraxe** [2015-Middleware-Keynote/demo-ansible#73]
this probably requires an improvement in the subscription manager module (`redhat_subscription`) but it appears that we are registering the hosts even if they are already registered:

```
TASK: [Enable subscription-manager] ******************************************* 
ok: [ec2-52-193-90-252.ap-northeast-1.compute.amazonaws.com]

TASK: [Register host] ********************************************************* 
changed: [ec2-52-193-90-252.ap-northeast-1.compute.amazonaws.com]
```

Especially with serialization in larger environments, this can take a lot of time...

If there was some way to check to see if the system was registered before bothering to run this step, it might save some time. Same with setting up the repos.

**Comment by detiber** [comment]
Closing now that https://github.com/2015-Middleware-Keynote/demo-ansible/pull/75 has merged
