### ISSUE TITLE
[rfe] combine register and post register

### ISSUE THREAD

**Issue by thoraxe** [2015-Middleware-Keynote/demo-ansible#74]
Does anyone remember/recall why we have separated register_hosts and post_register?

Especially if we're doing these in serial, it might make sense to do them all in one playbook. It can make big environments take quite a long time.

**Comment by detiber** [comment]
I do not recall other than it might have been an attempt to share common code between rhsm hosts and non-rhsm hosts.

In reality, we should probably leverage the subscription bits in openshift-ansible and use the repos variable for non-rhsm.

**Comment by thoraxe** [comment]
There are subscription bits in openshift-ansible now?

**Comment by detiber** [comment]
@thoraxe The original code was contributed by Amadeus and modified by @codificat, but I'm not sure I want to tackle modifying it to update for 3.1 (and future versions) quite yet...  Haven't put in enough thought on how to properly do it yet.

For now, I think keeping the demo-ansible registration bits separate is a good idea.

**Comment by thoraxe** [comment]
That's fine. What about combining the sub and repo-based activities into one playbook though?

**Comment by detiber** [comment]
Already done in my PR. Stuck on getting the registration stuff sorted out
right now (skipping re-reg on subsequent runs)

**Comment by detiber** [comment]
Closing now that https://github.com/2015-Middleware-Keynote/demo-ansible/pull/75 has merged
