### ISSUE TITLE
[RFE] README needs a list of valid AMIs

### ISSUE THREAD

**Issue by ryanj** [2015-Middleware-Keynote/demo-ansible#83]
I've been asked to add a list of AMIs to the README, better CLI usage examples.

**Comment by thoraxe** [comment]
The AMI list is dependent upon your Amazon account. We could maybe only refer to the hourly-charge public RHEL AMIs...

**Comment by kenthua** [comment]
Do you want to pick and choose what may be of value from here? 

https://github.com/kenthua/roadshow-ansible

**Comment by douglasawoods** [comment]
Yes.

Doug

**Comment by thoraxe** [comment]
@ryanj if you can fetch the list of hourly RHEL 7.2 AMIs from the regions that would be helpful. And/or submit a PR for a table.

@kenthua are your AMIs the standard hourly ones or cloud-access ones?

**Comment by kenthua** [comment]
@thoraxe The AMI's listed on the roadshow-ansible/README.md are the hourly ones, based on this search query `RHEL-7.2_HVM_GA-20151112-x86_64-1-Hourly2-GP2`

**Comment by thoraxe** [comment]
Done.
