### ISSUE TITLE
Evaluate oo_masters fails with "with_items expects a list or a set" using openshift-ansible:master

### ISSUE THREAD

**Issue by ryanj** [2015-Middleware-Keynote/demo-ansible#88]
Evaluate oo_masters fails with "with_items expects a list or a set":

```
TASK: [Evaluate oo_masters] *************************************************** 
fatal: [localhost] => with_items expects a list or a set
```

I think this error is happening here: https://github.com/2015-Middleware-Keynote/demo-ansible/blob/master/playbooks/openshift_setup.yml#L44

**Comment by detiber** [comment]
@ryanj this should be fixed in the latest master.

**Comment by ryanj** [comment]
the latest master is what I'm using (both repos)

**Comment by detiber** [comment]
@ryanj so, I _thought_ I had pushed a fix before I posted that update. It turns out I pushed it to my fork and not this repo.

I have now pushed the fix up to the correct repo.

**Comment by ryanj** [comment]
**FIXED**
Thanks, @detiber!
