### ISSUE TITLE
[rfe] Add tags to this repo to correlate to tested openshift enterprise versions

### ISSUE THREAD

**Issue by kenthua** [2015-Middleware-Keynote/demo-ansible#89]
Would it be possible to add tags to this repo, so that we can a snapshot version of what may work with which version of OpenShift Enterprise.  

This also relates to which openshift-ansible tags are viable for which versions of OpenShift Enterprise.  For instance some additions were added to openshift-ansible sometime after this [tag](https://github.com/openshift/openshift-ansible/tree/openshift-ansible-3.0.37-1) which caused the error between demo-ansible and openshift-ansible.  Which I recall was recently resolved.

**Comment by thoraxe** [comment]
In readme now.
