### ISSUE TITLE
[rfe] ability to specify which version of openshift enterprise to deploy

### ISSUE THREAD

**Issue by kenthua** [2015-Middleware-Keynote/demo-ansible#90]
This would allow for consistency and predictability of rollouts.  So that pre-testing performed for an existing roadshow does not get affected when a new version is released or in the processed of getting rolled out.

The best way would be to parameterize this in the run.py?

Currently it can be hardcoded in `openshift_setup.yml`, example [here](https://github.com/kenthua/roadshow-ansible/blob/master/playbooks/openshift_setup.yml#L67-L87)

**Comment by thoraxe** [comment]
This is a standard openshift-ansible installer option, so it wouldn't be hard to update run.py to accept an override.

**Comment by thoraxe** [comment]
This is hard-coded into the openshift_setup plays and is tested against specific tags of openshift-ansible.
