### ISSUE TITLE
[RFE] Add Metrics

### ISSUE THREAD

**Issue by christianh814** [2015-Middleware-Keynote/demo-ansible#96]
Add the ability to have the script enable cluster metrics for the environment

`--with-cluster-metrics`

Also (related to #95  ); have the storage back-end be the bucket storage set up with RFE #95 if S3 was specified. If not; have temp storage be used. 

NICE TO HAVE: The hawkular certificate should be the same as the wildcard cert so that you only have to accept the cert once.

**Comment by thoraxe** [comment]
Closed by #105
